name: viz
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - dtreeviz=1.3.3
  - graphviz
  - graphviz=2.40.1
  - ipython
  - ipywidgets=7.6.5
  - isort
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions
  - keras=2.4.3
  - matplotlib=3.5.0
  - mlxtend=0.19.0
  - mpmath
  - networkx
  - numpy=1.21.2
  - nxviz
  - opencv
  - pandas=1.4.1
  - pillow=9.2.0
  - plotly=5.1.0
  - pmdarima=1.8.5
  - pygraphviz
  - python=3.8.2
  - scikit-image
  - scikit-learn=1.0.2
  - scipy
  - seaborn=0.11.0
  - statsmodels=0.13.2
  - sympy
  - tensorboard=2.4.1
  - tensorflow
  - tensorflow=2.4.0
  - tqdm
  - xlrd